version: "3"
services:
  scrapper-service:
    build: "./scrapper-service"
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./scrapper-service:/opt/app

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discounts
